---
- name: Install Rsyslog package
  ansible.builtin.package:
    name: rsyslog
    state: present

- name: Deploy Rsyslog configuration file
  ansible.builtin.template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: "0640"
  notify: Restart Rsyslog
